### ISSUE TITLE
'make' error

### ISSUE THREAD

**Issue by luckypoem** [nmathewson/shim#2]
hi.

on my mac.
during the 'make' step,

yudeMacBook-Air:shim-by-nmathewson brite$ make
it shows:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [shim] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
yudeMacBook-Air:shim-by-nmathewson brite$

how to fix it?

**Comment by nmathewson** [comment]
Sorry, nobody has worked on this software since 2010.
